name: Setup Keystore (sekali)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Generate release keystore
        run: |
          keytool -genkeypair -v \
            -keystore release.jks \
            -alias tahfidz \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "Tahfidz4bbs!2026#R3l3as3" \
            -keypass "Tahfidz4bbs!2026#R3l3as3" \
            -dname "CN=Tahfidz SMP ABBS, OU=IT, O=SMP ABBS, L=Surakarta, ST=Jawa Tengah, C=ID" \
            -storetype JKS

      - name: Upload keystore
        uses: actions/upload-artifact@v4
        with:
          name: release-keystore
          path: release.jks